In [2]:
from viresclient import SwarmRequest
import datetime as dt
import numpy as np
import pandas as pd

request = SwarmRequest("https://staging.viresdisc.vires.services/openows")

In [3]:
request.available_collections()

General References:
 Swarm Data Handbook, https://earth.esa.int/web/guest/missions/esa-eo-missions/swarm/data-handbook 
 The Swarm Satellite Constellation Application and Research Facility (SCARF) and Swarm data products, https://doi.org/10.5047/eps.2013.07.001 
 Swarm Science Data Processing and Products (2013), https://link.springer.com/journal/40623/65/11/page/1 
 Special issue “Swarm science results after 2 years in space (2016), https://www.springeropen.com/collections/swsr 
 Earth's Magnetic Field: Understanding Geomagnetic Sources from the Earth's Interior and its Environment (2017), https://link.springer.com/journal/11214/206/1/page/1 

MAG
   SW_OPER_MAGA_LR_1B
   SW_OPER_MAGB_LR_1B
   SW_OPER_MAGC_LR_1B
 https://earth.esa.int/web/guest/missions/esa-eo-missions/swarm/data-handbook/level-1b-product-definitions#MAGX_LR_1B_Product 

IBI
   SW_OPER_IBIATMS_2F
   SW_OPER_IBIBTMS_2F
   SW_OPER_IBICTMS_2F
 https://earth.esa.int/web/guest/missions/esa-eo-missions/swarm/data-handbook/l

In [4]:
request.available_models()

CHAOS-6-Combined
CHAOS-6 Core + Static, NB: no magnetospheric part
 Recent geomagnetic secular variation from Swarm and ground observatories as estimated in the CHAOS-6 geomagnetic field model, http://doi.org/10.1186/s40623-016-0486-1 
 http://www.space.dtu.dk/english/Research/Scientific_data_and_models/Magnetic_Field_Models 

CHAOS-6-Core

CHAOS-6-Static

IGRF12
 International Geomagnetic Reference Field: the 12th generation, https://doi.org/10.1186/s40623-015-0228-9 
 https://www.ngdc.noaa.gov/IAGA/vmod/igrf.html 

MCO_SHA_2C
[Comprehensive Inversion]: Core field of CIY4
 A comprehensive model of Earth’s magnetic field determined from 4 years of Swarm satellite observations, https://doi.org/10.1186/s40623-018-0896-3 
Validation: ftp://swarm-diss.eo.esa.int/Level2longterm/MCO/SW_OPER_MCO_VAL_2C_20131201T000000_20180101T000000_0401.ZIP 

MCO_SHA_2D
[Dedicated Chain]: Core field
An algorithm for deriving core magnetic field models from the Swarm data set, https://doi.org/10.5047/eps.201

In [4]:
request.available_measurements("MAG")

['F',
 'dF_AOCS',
 'dF_other',
 'F_error',
 'B_VFM',
 'B_NEC',
 'dB_Sun',
 'dB_AOCS',
 'dB_other',
 'B_error',
 'q_NEC_CRF',
 'Att_error',
 'Flags_F',
 'Flags_B',
 'Flags_q',
 'Flags_Platform',
 'ASM_Freq_Dev']

##### Get all measurements from MAG, all auxiliaries, and some models

In [5]:
request.set_collection("SW_OPER_MAGA_LR_1B")

request.set_products(measurements=request.available_measurements()['MAG'],
                     models=["CHAOS-6-Core", "IGRF12", "MCO_SHA_2D"],
                     auxiliaries=request.available_auxiliaries(),
                     sampling_step="PT1S")

##### just one hour of data

In [7]:
start_time = dt.datetime(2014,1,1,0)
end_time = dt.datetime(2014,1,1,1)
data = request.get_between(start_time, end_time)

[1/1] Processing:  100%|██████████|  [ Elapsed: 00:02, Remaining: 00:00 ]
      Downloading: 100%|██████████|  [ Elapsed: 00:01, Remaining: 00:00 ] (2.463MB)


In [8]:
df = data.as_dataframe()
df.head()

ASM_Freq_Dev  AscendingNodeLongitude  AscendingNodeTime  \
Timestamp                                                                      
2014-01-01 00:00:00           0.0                 177.762       6.355575e+13   
2014-01-01 00:00:01           0.0                 177.762       6.355575e+13   
2014-01-01 00:00:02           0.0                 177.762       6.355575e+13   
2014-01-01 00:00:03           0.0                 177.762       6.355575e+13   
2014-01-01 00:00:04           0.0                 177.762       6.355575e+13   

                     Att_error  \
Timestamp                        
2014-01-01 00:00:00     1.1221   
2014-01-01 00:00:01     1.1575   
2014-01-01 00:00:02     1.2103   
2014-01-01 00:00:03     1.0741   
2014-01-01 00:00:04     1.2626   

                                                                 B_NEC  \
Timestamp                                                                
2014-01-01 00:00:00  [20103.559558498808, -4126.655257630182, -1008...   
2014-01-01 00:00:01  [20074.882005452877, -4130.142838761001, -1013...   
2014-01-01 00:00:02  [20046.14066295485, -4133.714088826309, -10173...   
2014-01-01 00:00:03  [20017.349310910515, -4137.184549771548, -1021...   
2014-01-01 00:00:04  [19988.565799488475, -4140.6369655162725, -102...   

                                                            B_NEC_AMPS  \
Timestamp                                                                
2014-01-01 00:00:00  [-1.355923605558535, 0.20631860625336002, 0.79...   
2014-01-01 00:00:01  [-1.3568484361468784, 0.20440798959228468, 0.7...   
2014-01-01 00:00:02  [-1.357929473789163, 0.202489650758499, 0.7681...   
2014-01-01 00:00:03  [-1.3591731609949194, 0.2005666020808496, 0.75...   
2014-01-01 00:00:04  [-1.3605853878322771, 0.19864171587044344, 0.7...   

                                                    B_NEC_CHAOS-6-Core  \
Timestamp                                                                
2014-01-01 00:00:00  [20112.993330287572, -4126.767668437053, -1008...   
2014-01-01 00:00:01  [20084.301619467966, -4130.387323832023, -1012...   
2014-01-01 00:00:02  [20055.573575989798, -4133.994970022446, -1016...   
2014-01-01 00:00:03  [20026.809613312344, -4137.590512415079, -1021...   
2014-01-01 00:00:04  [19998.010574496588, -4141.173938021151, -1025...   

                                                          B_NEC_IGRF12  \
Timestamp                                                                
2014-01-01 00:00:00  [20114.350961599408, -4131.807613989865, -1008...   
2014-01-01 00:00:01  [20085.643156314996, -4135.420336348679, -1012...   
2014-01-01 00:00:02  [20056.899265982334, -4139.020939766978, -1017...   
2014-01-01 00:00:03  [20028.11970634732, -4142.609331087865, -10215...   
2014-01-01 00:00:04  [19999.305322610322, -4146.185498869642, -1025...   

                                                      B_NEC_MCO_SHA_2D  \
Timestamp                                                                
2014-01-01 00:00:00  [20113.623599201284, -4127.464626156788, -1008...   
2014-01-01 00:00:01  [20084.934391641196, -4131.085872594489, -1012...   
2014-01-01 00:00:02  [20056.208873800508, -4134.695104868532, -1016...   
2014-01-01 00:00:03  [20027.447458666116, -4138.292228380256, -1021...   
2014-01-01 00:00:04  [19998.65098880975, -4141.877230155628, -10253...   

                                                                 B_VFM  \
Timestamp                                                                
2014-01-01 00:00:00  [-14523.552048799927, 1042.9656965421213, 1763...   
2014-01-01 00:00:01  [-14559.932775585665, 1047.3244563411865, 1759...   
2014-01-01 00:00:02  [-14596.18480765494, 1051.7844166317568, 17557...   
2014-01-01 00:00:03  [-14632.302244835888, 1056.1603804218048, 1752...   
2014-01-01 00:00:04  [-14668.219187530305, 1060.5329460102316, 1748...   

                                           ...                          \
Timestamp                        

In [9]:
# # xarray not yet supported for all measurements. It won't work here
# data.as_xarray()

In [10]:
df['q_NEC_CRF'].values  # one of the variables that I haven't added to xarray support

array([array([ 0.00520054,  0.00963281,  0.9987177 , -0.04942798]),
       array([ 0.00520175,  0.00964689,  0.99871854, -0.04940803]),
       array([ 0.00520298,  0.00966073,  0.99871939, -0.04938804]), ...,
       array([ 3.69872000e-04, -1.55320000e-04,  3.75593200e-03, -9.99992866e-01]),
       array([ 3.41053000e-04, -1.60571000e-04,  3.82193100e-03, -9.99992625e-01]),
       array([ 3.12614000e-04, -1.65852000e-04,  3.88808400e-03, -9.99992379e-01])],
      dtype=object)

In [12]:
df['QDBasis'].iloc[0]

array([[ 0.96518731,  0.14590079],
       [-0.20921698,  1.05164397]])

In [13]:
data.to_file('testmag.cdf', overwrite=True)

Data written to testmag.cdf


In [14]:
import cdflib
import numpy as np

cdf = cdflib.CDF('testmag.cdf')
cdf.cdf_info()

{'Attributes': [{'CREATED': 'Global'},
  {'CREATOR': 'Global'},
  {'UNITS': 'Variable'},
  {'DESCRIPTION': 'Variable'},
  {'FIELDNAM': 'Variable'},
  {'SCALEMAX': 'Variable'},
  {'VAR_TYPE': 'Variable'},
  {'FORMAT': 'Variable'},
  {'VALIDMIN': 'Variable'},
  {'CATDESC': 'Variable'},
  {'DEPEND_0': 'Variable'},
  {'VALIDMAX': 'Variable'},
  {'DISPLAY_TYPE': 'Variable'},
  {'FILLVAL': 'Variable'},
  {'LABLAXIS': 'Variable'},
  {'SCALEMIN': 'Variable'},
  {'TITLE': 'Global'},
  {'SOURCES': 'Global'},
  {'MAGNETIC_MODELS': 'Global'},
  {'ORIGINAL_PRODUCT_NAMES': 'Global'},
  {'DATA_FILTERS': 'Global'},
  {'DATA_TIMESPAN': 'Global'}],
 'CDF': 'testmag.cdf',
 'Checksum': False,
 'Compressed': False,
 'Copyright': '\nCommon Data Format (CDF)\n(C) Copyright 1990-2015 NASA/GSFC\nSpace Physics Data Facility\nNASA/Goddard Space Flight Center\nGreenbelt, Maryland 20771 USA\n(Internet -- GSFC-CDF-SUPPORT@LISTS.NASA.GOV)\n',
 'Encoding': 6,
 'Majority': 'Row_major',
 'Num_rdim': 0,
 'Version': '2.7

In [15]:
cdf.varinq("QDBasis")

{'Block_Factor': 0,
 'Compress': 0,
 'Data_Type': 45,
 'Data_Type_Description': 'CDF_DOUBLE',
 'Dim_Sizes': [2, 2],
 'Dim_Vary': [True, True],
 'Last_Rec': 3599,
 'Num': 41,
 'Num_Dims': 2,
 'Num_Elements': 1,
 'Pad': array([0.]),
 'Rec_Vary': True,
 'Sparse': 'No_sparse',
 'Var_Type': 'zVariable',
 'Variable': 'QDBasis'}

In [16]:
cdf.varget("QDBasis")

array([[[ 0.96518731,  0.14590079],
        [-0.20921698,  1.05164397]],

       [[ 0.96445704,  0.14612697],
        [-0.20949209,  1.05176282]],

       [[ 0.96372646,  0.14635366],
        [-0.20976678,  1.05188096]],

       ...,

       [[ 1.05074775, -0.01943285],
        [ 0.06867066,  0.94404292]],

       [[ 1.05091155, -0.01941218],
        [ 0.06903298,  0.94402194]],

       [[ 1.05107486, -0.01939242],
        [ 0.06939636,  0.94400108]]])